fix PS1

diff --git a/shell/bashrc b/shell/bashrc
--- a/shell/bashrc
+++ b/shell/bashrc
@@ -105,10 +105,13 @@ if [ -f /usr/lib/git-core/git-sh-prompt ]; then
 fi
 
 export GIT_PS1_SHOWDIRTYSTATE=1
-PS1=$'$(tput sgr0)$(printf %03d $?)$(tput sgr0) | $(tput setaf 2)\u@\H$(tput setaf 4) \\t $(tput setaf 3)[\w]$(tput setaf 1)$(__git_ps1)
+# Capture the previous command's exit code first, before PS1's own command
+# substitutions (e.g. $(tput sgr0)) run and clobber $? back to 0.
+PROMPT_COMMAND='__last_exit=$?'
+PS1=$'$(tput sgr0)$(printf %03d $__last_exit)$(tput sgr0) | $(tput setaf 2)\u@\H$(tput setaf 4) \\t $(tput setaf 3)[\w]$(tput setaf 1)$(__git_ps1)
 \\[$(tput sgr0)\\]-> % '
 # this shares history across tmux panes - https://askubuntu.com/a/1352448
-PROMPT_COMMAND="history -a; history -c; history -r"
+#PROMPT_COMMAND="history -a; history -c; history -r"
 
 export IGNOREEOF=3
 
